### ISSUE TITLE
Option to keep password

### ISSUE THREAD

**Issue by cwygoda** [ANXS/generic-users#10]
Right now the password gets set, even if the user exists and has a password set. Please enable the use of the update_password option.

**Comment by soupdiver** [comment]
Where do you store your user passwords when not putting in in the variable?

**Comment by arsgeografica** [comment]
I want to specify my users and the initial password I create for them, but actually I don't want to manage their passwords over time, it should be left up to them.

**Comment by soupdiver** [comment]
https://github.com/ANXS/generic-users/blob/master/tasks/main.yml#L22

The default is to omit the password if not set. So simply remove the password attribute from the `genericusers_users` variable and should not be changed
