### ISSUE TITLE
Issue with 'Make sure the users are present' on Ansible 1.6.8

### ISSUE THREAD

**Issue by pusewicz** [ANXS/generic-users#3]
```
TASK: [Ansibles.generic-users | generic-users | Make sure the users are present] *** 
fatal: [vagrant] => A variable inserted a new parameter into the module args. Be sure to quote variables if they contain equal signs (for example: "{{var}}").
```

**Comment by pjan** [comment]
@soupdiver if you fancy to have a shot at this? You might have to update the `.travis.yml` configuration so it's not forcefully checking out ansible, but a newer version. The `Readme.md` would have to be updated as well to reflect the minimum version requirement.

**Comment by soupdiver** [comment]
@pjan It's already on my list :)
